version: '3.7'
services:
  nest-api:
    container_name: gos-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gosbe@11
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql:
    name: gos-db