# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
#   pull_request:
#     branches: [ main ]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy appication
      uses:  appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_GOS  }}        
        username: ${{ secrets.SSH_USERNAME_GOS }}      
        password: ${{ secrets.SSH_PWD_GOS }}
        port: 22
        script_stop: true
        script: | 
          cd ~/gos-be
          sudo docker-compose -f docker-compose.yml down
          sudo git pull origin main
          sudo docker-compose -f docker-compose.yml up -d --build 


